<a href="https://colab.research.google.com/github/no-akatsu/training/blob/main/240930_%E7%B7%9A%E5%BD%A2%E5%9B%9E%E5%B8%B0_%E3%82%B9%E3%82%AF%E3%83%A9%E3%83%83%E3%83%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import

In [14]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

# Model

In [31]:
class LinearRegression:
    def __init__(self, lr=0.01, epochs=1000):
        # 初期値として、learning rate、epoch数、重みW、
        self.lr = lr
        self.epochs = epochs
        self.W = None
        self.b = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.W = np.zeros(n_features)
        self.b = 0

        for epoch in range(self.epochs):
            y_pred = np.dot(X, self.W) + self.b

            # 勾配の計算
            dw = (1/n_samples) * np.dot(X.T, (y_pred - y))
            db = (1/n_samples) * np.sum(y_pred - y)

            # 重みとバイアスの更新
            self.W -= self.lr * dw
            self.b -= self.lr * db

            if epoch % 100 == 0:
                print(f'Epoch: {epoch}, Loss: {dw}')


    def predict(self, X):
        return np.dot(X, self.W) + self.b

In [32]:
# データをロード
california_housing = fetch_california_housing()
X = california_housing.data[:, np.newaxis, 2]
y = california_housing.target

In [34]:
X, X.shape

(array([[6.98412698],
        [6.23813708],
        [8.28813559],
        ...,
        [5.20554273],
        [5.32951289],
        [5.25471698]]),
 (20640, 1))

In [35]:
y, y.shape

(array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), (20640,))

In [36]:
# データをトレーニングセットとテストセットに分割
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# モデルの作成と学習
model = LinearRegression(lr=0.01, epochs=1000)
model.fit(X_train, y_train)

Epoch: 0, Loss: [-11.69896506]
Epoch: 100, Loss: [0.03351859]
Epoch: 200, Loss: [0.02861778]
Epoch: 300, Loss: [0.02443353]
Epoch: 400, Loss: [0.02086106]
Epoch: 500, Loss: [0.01781093]
Epoch: 600, Loss: [0.01520676]
Epoch: 700, Loss: [0.01298336]
Epoch: 800, Loss: [0.01108504]
Epoch: 900, Loss: [0.00946428]


In [37]:
# 学習後の重みとバイアスを表示
print('学習された重み（W）:', model.W)
print('学習されたバイアス（b）:', model.b)

学習された重み（W）: [0.12791504]
学習されたバイアス（b）: 1.3245411859046894


In [38]:
y_pred = model.predict(X_test)
y_pred

array([1.86078667, 1.96915411, 1.83327907, ..., 2.25034877, 2.00108759,
       1.8347737 ])